/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <div className="items-stretch bg-white flex flex-col">
      <div className="items-stretch bg-white flex w-full flex-col">
        <div className="bg-white flex w-full flex-col pt-7 pb-5 px-4">
          <div className="justify-between items-stretch flex w-[219px] max-w-full gap-5">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f2f54e2a-dafb-4bb5-b5b6-cc252462f915?apiKey=e48314d4075e42db972478e94e0afa25&"
              className="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
            />
            <div className="text-stone-900 text-lg font-bold leading-6 tracking-tight whitespace-nowrap">
              HireRight
            </div>
          </div>
        </div>
        <div className="flex w-full flex-col items-stretch mt-3 px-3.5">
          <div className="justify-between items-center bg-lime-50 flex w-full flex-col px-4 py-3 rounded-3xl">
            <div className="items-stretch flex w-full max-w-[297px] gap-4">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a72eec6f-25af-4266-9996-89ab1834b905?apiKey=e48314d4075e42db972478e94e0afa25&"
                className="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
              />
              <div className="text-stone-500 text-base leading-6 whitespace-nowrap">
                Search for candidates or job titles
              </div>
            </div>
          </div>
          <div className="items-stretch flex justify-between gap-5 mt-6 max-md:justify-center">
            <div className="text-stone-900 text-sm font-medium leading-5 whitespace-nowrap justify-center items-stretch bg-lime-50 aspect-[1.5] px-4 py-1.5 rounded-2xl">
              All
            </div>
            <div className="text-stone-900 text-sm font-medium leading-5 whitespace-nowrap justify-center items-stretch bg-lime-50 aspect-[2] px-4 py-1.5 rounded-2xl">
              Tech
            </div>
            <div className="text-stone-900 text-sm font-medium leading-5 whitespace-nowrap justify-center items-stretch bg-lime-50 grow px-4 py-1.5 rounded-2xl">
              Marketing
            </div>
            <div className="text-stone-900 text-sm font-medium leading-5 whitespace-nowrap justify-center items-stretch bg-lime-50 grow px-4 py-1.5 rounded-2xl">
              Design
            </div>
          </div>
          <div className="text-stone-900 text-2xl font-bold leading-7 tracking-tight whitespace-nowrap mt-7">
            Recommended for you
          </div>
          <div className="items-stretch flex justify-between gap-4 mt-7 pr-6 max-md:pr-5">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/b19b720e-fc75-48cd-8658-b07a2c047da5?apiKey=e48314d4075e42db972478e94e0afa25&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/b19b720e-fc75-48cd-8658-b07a2c047da5?apiKey=e48314d4075e42db972478e94e0afa25&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b19b720e-fc75-48cd-8658-b07a2c047da5?apiKey=e48314d4075e42db972478e94e0afa25&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/b19b720e-fc75-48cd-8658-b07a2c047da5?apiKey=e48314d4075e42db972478e94e0afa25&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/b19b720e-fc75-48cd-8658-b07a2c047da5?apiKey=e48314d4075e42db972478e94e0afa25&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b19b720e-fc75-48cd-8658-b07a2c047da5?apiKey=e48314d4075e42db972478e94e0afa25&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/b19b720e-fc75-48cd-8658-b07a2c047da5?apiKey=e48314d4075e42db972478e94e0afa25&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/b19b720e-fc75-48cd-8658-b07a2c047da5?apiKey=e48314d4075e42db972478e94e0afa25&"
              className="aspect-square object-contain object-center w-32 overflow-hidden shrink-0 max-w-full"
            />
            <div className="justify-center items-stretch self-center flex grow basis-[0%] flex-col my-auto">
              <div className="text-stone-900 text-2xl font-bold leading-7 tracking-tight whitespace-nowrap">
                Jane Doe
              </div>
              <div className="text-stone-500 text-base leading-6 whitespace-nowrap">
                Senior Software Engineer
              </div>
            </div>
          </div>
          <div className="items-stretch flex justify-between gap-3 mt-4 pr-1">
            <div className="justify-center items-center bg-lime-50 flex grow basis-[0%] flex-col px-5 py-2.5 rounded-3xl">
              <div className="text-stone-900 text-sm font-bold leading-5 tracking-wide whitespace-nowrap items-stretch bg-lime-50 w-[83px] max-w-full">
                View Profile
              </div>
            </div>
            <div className="justify-center items-center bg-emerald-600 flex grow basis-[0%] flex-col px-5 py-2.5 rounded-3xl">
              <div className="text-white text-sm font-bold leading-5 tracking-wide whitespace-nowrap items-stretch bg-emerald-600 aspect-[2.8095238095238093]">
                Shortlist
              </div>
            </div>
          </div>
          <div className="items-stretch flex justify-between gap-4 mt-8">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/63ad776c-f401-494c-8c8e-08b1f77b9908?apiKey=e48314d4075e42db972478e94e0afa25&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/63ad776c-f401-494c-8c8e-08b1f77b9908?apiKey=e48314d4075e42db972478e94e0afa25&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/63ad776c-f401-494c-8c8e-08b1f77b9908?apiKey=e48314d4075e42db972478e94e0afa25&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/63ad776c-f401-494c-8c8e-08b1f77b9908?apiKey=e48314d4075e42db972478e94e0afa25&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/63ad776c-f401-494c-8c8e-08b1f77b9908?apiKey=e48314d4075e42db972478e94e0afa25&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/63ad776c-f401-494c-8c8e-08b1f77b9908?apiKey=e48314d4075e42db972478e94e0afa25&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/63ad776c-f401-494c-8c8e-08b1f77b9908?apiKey=e48314d4075e42db972478e94e0afa25&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/63ad776c-f401-494c-8c8e-08b1f77b9908?apiKey=e48314d4075e42db972478e94e0afa25&"
              className="aspect-square object-contain object-center w-32 overflow-hidden shrink-0 max-w-full"
            />
            <div className="justify-center items-stretch self-center flex grow basis-[0%] flex-col my-auto">
              <div className="text-stone-900 text-2xl font-bold leading-7 tracking-tight whitespace-nowrap">
                John Smith
              </div>
              <div className="text-stone-500 text-base leading-6 whitespace-nowrap">
                Data Scientist
              </div>
            </div>
          </div>
          <div className="items-stretch flex justify-between gap-3 mt-4 pr-1">
            <div className="justify-center items-center bg-lime-50 flex grow basis-[0%] flex-col px-5 py-2.5 rounded-3xl">
              <div className="text-stone-900 text-sm font-bold leading-5 tracking-wide whitespace-nowrap items-stretch bg-lime-50 w-[83px] max-w-full">
                View Profile
              </div>
            </div>
            <div className="justify-center items-center bg-emerald-600 flex grow basis-[0%] flex-col px-5 py-2.5 rounded-3xl">
              <div className="text-white text-sm font-bold leading-5 tracking-wide whitespace-nowrap items-stretch bg-emerald-600 aspect-[2.8095238095238093]">
                Shortlist
              </div>
            </div>
          </div>
          <div className="justify-center items-center bg-white flex flex-col mt-7 px-5 py-2.5 rounded-3xl">
            <div className="text-stone-900 text-sm font-bold leading-5 tracking-wide whitespace-nowrap items-stretch bg-white w-[202px] max-w-full">
              See more recommendations
            </div>
          </div>
        </div>
        <div className="items-stretch bg-white flex w-full flex-col mt-3 px-4 py-3 border-t-lime-50 border-t border-solid">
          <div className="flex justify-between gap-3.5 pl-3.5 pr-3 py-0.5 max-md:justify-center">
            <div className="items-stretch flex basis-[0%] flex-col">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9a25a3a8-bf23-4321-b39d-a09efaf96c7a?apiKey=e48314d4075e42db972478e94e0afa25&"
                className="aspect-[1.5] object-contain object-center w-9 overflow-hidden"
              />
              <div className="text-stone-900 text-center text-xs font-medium leading-5 tracking-normal whitespace-nowrap mt-2">
                Home
              </div>
            </div>
            <div className="items-center flex grow basis-[0%] flex-col">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b793174-a11e-4225-9d26-9cd9c61aaed8?apiKey=e48314d4075e42db972478e94e0afa25&"
                className="aspect-square object-contain object-center w-6 overflow-hidden"
              />
              <div className="text-stone-500 text-center text-xs font-medium leading-5 tracking-normal self-stretch whitespace-nowrap mt-2">
                Search
              </div>
            </div>
            <div className="items-center flex grow basis-[0%] flex-col">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/436e2150-6b5f-447a-8cdc-0f26952a1f54?apiKey=e48314d4075e42db972478e94e0afa25&"
                className="aspect-square object-contain object-center w-6 overflow-hidden max-w-full"
              />
              <div className="text-stone-500 text-center text-xs font-medium leading-5 tracking-normal self-stretch whitespace-nowrap mt-2">
                Shortlist
              </div>
            </div>
            <div className="items-center flex grow basis-[0%] flex-col">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/e0796da5-f835-4449-9ec6-e64d2b4a0884?apiKey=e48314d4075e42db972478e94e0afa25&"
                className="aspect-square object-contain object-center w-6 overflow-hidden max-w-full"
              />
              <div className="text-stone-500 text-center text-xs font-medium leading-5 tracking-normal self-stretch whitespace-nowrap mt-2">
                Notifications
              </div>
            </div>
            <div className="items-stretch flex grow basis-[0%] flex-col">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9b12f100-eabc-48b3-9dd0-18ab1a211d5c?apiKey=e48314d4075e42db972478e94e0afa25&"
                className="aspect-[1.58] object-contain object-center w-[38px] overflow-hidden"
              />
              <div className="text-stone-500 text-center text-xs font-medium leading-5 tracking-normal whitespace-nowrap mt-2">
                Profile
              </div>
            </div>
          </div>
        </div>
        <div className="items-start bg-white flex min-h-[20px] w-full flex-col" />
      </div>
    </div>
  );
}
